# Generated by Django 4.2.1 on 2023-10-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_can_update_bank_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_verify_it_purchases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_finance_officer',
            field=models.BooleanField(default=False),
        ),
    ]
