# Generated by Django 4.2.1 on 2023-10-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_can_verify_it_purchases_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='can_verify_it_purchases',
            new_name='can_verify_purchases',
        ),
    ]
