# Generated by Django 4.2.1 on 2023-07-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
