# Generated by Django 4.2.1 on 2023-07-25 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0004_cashadvanceform_is_completed_cashadvanceformreceiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashadvanceform',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashadvanceform',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashadvanceform',
            name='invoice_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cashadvanceform',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ProjectManager',
        ),
    ]
