# Generated by Django 4.2.1 on 2023-07-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_cashadvanceform_approver_cashadvanceform_checker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashadvanceform',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
