# Generated by Django 4.2.1 on 2023-07-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_cashadvanceform_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetline',
            name='description',
        ),
    ]
