# Generated by Django 4.2.1 on 2023-07-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_budgetline_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountreceived',
            name='signature',
        ),
        migrations.AddField(
            model_name='amountreceived',
            name='receipt',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
