# Generated by Django 4.2.1 on 2023-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_cashadvanceform_country_cashadvanceform_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cashadvanceform',
            name='bank_batch_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
