# Generated by Django 4.2.1 on 2023-10-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_rename_expense_incured_expenseclaimform_expense_incurred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseclaimform',
            name='expense_incurred',
        ),
    ]
