# Generated by Django 4.2.1 on 2023-10-15 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_remove_expenseclaimform_expense_incurred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequisitionform',
            old_name='items_required_by',
            new_name='date_required',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionform',
            name='budget_line',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionform',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionform',
            name='checker',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionform',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionform',
            name='reason',
        ),
        migrations.AddField(
            model_name='purchaserequisitionform',
            name='budget_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequisitionform',
            name='confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_confirmed_by', to='accounting.formuser'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionform',
            name='requisition_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisitionform',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_verified_by', to='accounting.formuser'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionform',
            name='delivered_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
