# Generated by Django 4.2.1 on 2023-10-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_rename_warranty_period_requestforquotationform_warrant_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforquotationform',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
