# Generated by Django 4.2.1 on 2023-10-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_requestforquotationform_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforquotationform',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
