# Generated by Django 4.2.1 on 2023-10-17 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_requestforquotationform_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpurchaseorderform',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='localpurchaseorderform',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.project'),
        ),
        migrations.AddField(
            model_name='localpurchaseorderform',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='overexpenditureform',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='overexpenditureform',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='underexpenditureform',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='underexpenditureform',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='overexpenditureform',
            name='project_code',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
