# Generated by Django 4.2.1 on 2023-10-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_localpurchaseorderform_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='underexpenditureform',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='underexpenditureform',
            name='amount_deposited',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='underexpenditureform',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='underexpenditureform',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='underexpenditureform',
            name='ref_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='underexpenditureform',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
