# Generated by Django 4.2.1 on 2023-10-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_underexpenditureform_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashadvanceform',
            name='max_level',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='expenseclaimform',
            name='max_level',
            field=models.IntegerField(default=4),
        ),
    ]
