# Generated by Django 4.2.1 on 2023-10-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_alter_expenseclaimform_amount_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisitionform',
            name='max_level',
            field=models.IntegerField(default=4),
        ),
    ]
