# Generated by Django 4.2.1 on 2023-10-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_purchaserequisitionform_max_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpurchaseorderform',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='localpurchaseorderform',
            name='max_level',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='requestforquotationform',
            name='max_level',
            field=models.IntegerField(default=1),
        ),
    ]
