# Generated by Django 4.2.1 on 2023-10-26 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0028_localpurchaseorderform_budget_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpurchaseorderform',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_purchase_order_approved_by', to='accounting.formuser'),
        ),
        migrations.AddField(
            model_name='localpurchaseorderform',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_purchase_order_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
