# Generated by Django 4.2.1 on 2023-10-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_localpurchaseorderform_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpurchaseorderform',
            name='delivery_period',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='localpurchaseorderform',
            name='price_validity_period',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='localpurchaseorderform',
            name='warrant_period',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
