# Generated by Django 4.2.1 on 2023-10-26 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0031_alter_localpurchaseorderform_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overexpenditureform',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='over_expenditure_approved_by', to='accounting.formuser'),
        ),
        migrations.AlterField(
            model_name='overexpenditureform',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='over_expenditure_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='overexpenditureform',
            name='bank_batch_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overexpenditureform',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='over_expenditure_checked_by', to='accounting.formuser'),
        ),
        migrations.AlterField(
            model_name='overexpenditureform',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='over_expenditure_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='overexpenditureform',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='underexpenditureform',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='under_expenditure_approved_by', to='accounting.formuser'),
        ),
        migrations.AlterField(
            model_name='underexpenditureform',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='under_expenditure_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='underexpenditureform',
            name='bank_batch_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='underexpenditureform',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='under_expenditure_checked_by', to='accounting.formuser'),
        ),
        migrations.AlterField(
            model_name='underexpenditureform',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='under_expenditure_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='underexpenditureform',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='underexpenditureform',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
