# Generated by Django 4.2.1 on 2023-10-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_alter_overexpenditureform_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overexpenditureform',
            name='max_level',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='underexpenditureform',
            name='max_level',
            field=models.IntegerField(default=3),
        ),
    ]
