# Generated by Django 4.2.1 on 2023-10-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_overexpenditureform_max_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overexpenditureform',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overexpenditureform',
            name='payee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='underexpenditureform',
            name='payee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
