# Generated by Django 4.2.1 on 2023-10-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_overexpenditureform_date_overexpenditureform_payee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overexpenditureform',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
